FROM ubuntu:22.04 AS base

SHELL ["/bin/bash", "-c"]

ENV root_dir /tmp/zoom_bot
ENV project bots/zoom_bot
ENV cwd $root_dir/$project

ARG DEBIAN_FRONTEND=noninteractive

WORKDIR $cwd
#  Install Dependencies
RUN apt-get update  \
    && apt-get install -y \
    build-essential \
    ca-certificates \
    cmake \
    curl \
    gdb \
    git \
    gfortran \
    libopencv-dev \
    libdbus-1-3 \
    libgbm1 \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libglib2.0-dev \
    libssl-dev \
    libx11-dev \
    libx11-xcb1 \
    libxcb-image0 \
    libxcb-keysyms1 \
    libxcb-randr0 \
    libxcb-shape0 \
    libxcb-shm0 \
    libxcb-xfixes0 \
    libxcb-xtest0 \
    libgl1-mesa-dri \
    libxfixes3 \
    linux-libc-dev \
    pkgconf \
    tar \
    unzip \
    zip \
    python3 \
    python3-pip
    
RUN pip install --no-cache-dir \
    google-cloud-speech \
    google-generativeai \
    jinja2 \
    deepgram-sdk \
    python-dotenv
# Install ALSA
RUN apt-get install -y libasound2 libasound2-plugins alsa alsa-utils alsa-oss

# Install Pulseaudio
RUN apt-get install -y  pulseaudio pulseaudio-utils

FROM base AS deps

ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

WORKDIR /opt
RUN git clone --depth 1 https://github.com/Microsoft/vcpkg.git \
    && ./vcpkg/bootstrap-vcpkg.sh -disableMetrics \
    && ln -s /opt/vcpkg/vcpkg /usr/local/bin/vcpkg \
    && vcpkg install vcpkg-cmake

FROM deps AS build

WORKDIR $cwd
ENTRYPOINT ["/tini", "--", "./bots/zoom_bot/bin/entry.sh"]

WORKDIR $root_dir
CMD ["python", "main.py", "-t","g", "-n", "TempUser"]
